WebApplicationFLexElectronicsShop_ProjectRazorPages/Pages/DigitalProducts/Add.cshtml.cs
using FLexElectronicsShop.Data;
using FLexElectronicsShop.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FLexElectronicsShop.Pages.DigitalProducts
{
    public class AddModel(FEShopContext fEShopContext) : PageModel
    {
        public void OnGet()
        {
        }

        [BindProperty]
        public Product product { get; set; }
        public async Task<IActionResult> OnPostAsync()
        {
            if (product is null || !ModelState.IsValid)
            {
                return Page();
            }

            await fEShopContext.Products.AddAsync(product);
            await fEShopContext.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

WebApplicationFLexElectronicsShop_ProjectRazorPages/Pages/DigitalProducts/Delete.cshtml.cs
using FLexElectronicsShop.Data;
using FLexElectronicsShop.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace FLexElectronicsShop.Pages.DigitalProducts
{
    public class DeleteModel(FEShopContext fEShopContext) : PageModel
    {
        public Product? Product { get; set; }
        public async Task OnGetAsync(int id)
        {
            Product = await fEShopContext.Products.FirstAsync(product => product.Id == id);
        }

        public async Task<IActionResult> OnPostDeleteAsync(int id)
        {

            var digproduct = await fEShopContext.Products.FirstAsync(movie => movie.Id == id);
            fEShopContext.Products.Remove(digproduct);
            await fEShopContext.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

WebApplicationFLexElectronicsShop_ProjectRazorPages/Pages/DigitalProducts/Details.cshtml.cs
using FLexElectronicsShop.Data;
using FLexElectronicsShop.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace FLexElectronicsShop.Pages.DigitalProducts
{
    public class DetailsModel(FEShopContext fEShopContext) : PageModel
    {
        public Product Product { get; set; }
        public async Task OnGetAsync(int id)
        {
            Product = await fEShopContext.Products.FirstAsync(p => p.Id == id);
        }
    }
}

WebApplicationFLexElectronicsShop_ProjectRazorPages/Pages/DigitalProducts/Edit.cshtml.cs
using FLexElectronicsShop.Data;
using FLexElectronicsShop.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace FLexElectronicsShop.Pages.DigitalProducts
{
    public class EditModel(FEShopContext fEShopContext) : PageModel
    {
        [BindProperty]
        public Product Product { get; set; }
        public async Task OnGetAsync(int id)
        {
            Product = await fEShopContext.Products.FirstAsync(p => p.Id == id);

        }

        public async Task<IActionResult> OnPostUpdateAsync(int id)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            var updateProduct = await fEShopContext.Products.FirstAsync(p => p.Id == id);
            updateProduct!.Name = Product!.Name;
            updateProduct.URL = Product!.URL;
            updateProduct.Description = Product!.Description;
            //updateProduct.Price = Product!.Price;
            await fEShopContext.SaveChangesAsync();


            return RedirectToPage("./Index");
        }
    }
}

WebApplicationFLexElectronicsShop_ProjectRazorPages/Pages/DigitalProducts/Index.cshtml.cs
using FLexElectronicsShop.Data;
using FLexElectronicsShop.Model;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace FLexElectronicsShop.Pages.DigitalProducts
{
    public class IndexModel(FEShopContext eShopContext) : PageModel
    {
        public IList<Product> Products { get; set; }
        public SelectList Categories { get; set; }
        [BindProperty(SupportsGet = true)]
        public int? SelectedCategoryId { get; set; }

        public async Task OnGetAsync()
        {
            Categories = new SelectList(await eShopContext.Categories.ToListAsync(), "Id", "Name");

            IQueryable<Product> productsQuery = eShopContext.Products.Include(p => p.Category);

            if (SelectedCategoryId.HasValue)
            {
                productsQuery = productsQuery.Where(p => p.Category.Id == SelectedCategoryId.Value);
            }

            Products = await productsQuery.ToListAsync();
        }
    }
}

WebApplicationFLexElectronicsShop_ProjectRazorPages/Pages/StoreManagement/CategoryManagement/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using FLexElectronicsShop.Data;
using FLexElectronicsShop.Model;

namespace FLexElectronicsShop.Pages.StoreManagement.CategoryManagement
{
    public class DeleteModel : PageModel
    {
        private readonly FLexElectronicsShop.Data.FEShopContext _context;

        public DeleteModel(FLexElectronicsShop.Data.FEShopContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Category Category { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.FirstOrDefaultAsync(m => m.Id == id);

            if (category == null)
            {
                return NotFound();
            }
            else
            {
                Category = category;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.FindAsync(id);
            if (category != null)
            {
                Category = category;
                _context.Categories.Remove(Category);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

WebApplicationFLexElectronicsShop_ProjectRazorPages/Pages/StoreManagement/CategoryManagement/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using FLexElectronicsShop.Data;
using FLexElectronicsShop.Model;

namespace FLexElectronicsShop.Pages.StoreManagement.CategoryManagement
{
    public class DetailsModel : PageModel
    {
        private readonly FLexElectronicsShop.Data.FEShopContext _context;

        public DetailsModel(FLexElectronicsShop.Data.FEShopContext context)
        {
            _context = context;
        }

        public Category Category { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }
            else
            {
                Category = category;
            }
            return Page();
        }
    }
}

WebApplicationFLexElectronicsShop_ProjectRazorPages/Pages/StoreManagement/CategoryManagement/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FLexElectronicsShop.Data;
using FLexElectronicsShop.Model;

namespace FLexElectronicsShop.Pages.StoreManagement.CategoryManagement
{
    public class EditModel : PageModel
    {
        private readonly FLexElectronicsShop.Data.FEShopContext _context;

        public EditModel(FLexElectronicsShop.Data.FEShopContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Category Category { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category =  await _context.Categories.FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }
            Category = category;
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Category).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!CategoryExists(Category.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool CategoryExists(int id)
        {
            return _context.Categories.Any(e => e.Id == id);
        }
    }
}

WebApplicationFLexElectronicsShop_ProjectRazorPages/Pages/StoreManagement/ProductManagement/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using FLexElectronicsShop.Data;
using FLexElectronicsShop.Model;

namespace FLexElectronicsShop.Pages.StoreManagement.ProductManagement
{
    public class DeleteModel : PageModel
    {
        private readonly FLexElectronicsShop.Data.FEShopContext _context;

        public DeleteModel(FLexElectronicsShop.Data.FEShopContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Product Product { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products.FirstOrDefaultAsync(m => m.Id == id);

            if (product == null)
            {
                return NotFound();
            }
            else
            {
                Product = product;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products.FindAsync(id);
            if (product != null)
            {
                Product = product;
                _context.Products.Remove(Product);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

WebApplicationFLexElectronicsShop_ProjectRazorPages/Pages/StoreManagement/ProductManagement/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using FLexElectronicsShop.Data;
using FLexElectronicsShop.Model;

namespace FLexElectronicsShop.Pages.StoreManagement.ProductManagement
{
    public class DetailsModel : PageModel
    {
        private readonly FLexElectronicsShop.Data.FEShopContext _context;

        public DetailsModel(FLexElectronicsShop.Data.FEShopContext context)
        {
            _context = context;
        }

        public Product Product { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products.FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }
            else
            {
                Product = product;
            }
            return Page();
        }
    }
}

WebApplicationFLexElectronicsShop_ProjectRazorPages/Pages/StoreManagement/ProductManagement/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FLexElectronicsShop.Data;
using FLexElectronicsShop.Model;
using FLexElectronicsShop.Services.Interfaces;
using FLexElectronicsShop.ViewModel;

namespace FLexElectronicsShop.Pages.StoreManagement.ProductManagement
{
    public class EditModel : PageModel
    {
        private readonly FLexElectronicsShop.Data.FEShopContext _context;
        private IPhotoService PhotoService;
        public EditModel(FLexElectronicsShop.Data.FEShopContext context, IPhotoService photoService)
        {
            _context = context;
            PhotoService = photoService;
        }

        [BindProperty]
        public ProductViewModel Product { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product =  await _context.Products.FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }
            Product = new ProductViewModel
            {
                Id = product.Id,
                Title = product.Name,
                Description = product.Description,
                CategoryId = product.CategoryId,
                URL = null
            };
           ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Description");
            return Page();
        }


        public async Task<IActionResult> OnPostAsync(int id)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var product = await _context.Products.FirstOrDefaultAsync(p => p.Id == Product.Id);

            if(Product.URL is not null)
            {
                await PhotoService.DeletePhotoAsync(product.URL);
                var resultAddPhoto = await PhotoService.AddPhotoAsync(Product.URL);
                product.URL = resultAddPhoto.Url.ToString();
            }

            product.Name = Product.Title;
            product.Description = Product.Description;
            product.CategoryId = Product.CategoryId;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ProductExists(Product.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool ProductExists(int id)
        {
            return _context.Products.Any(e => e.Id == id);
        }
    }
}

WebApplicationFLexElectronicsShop_ProjectRazorPages/Pages/StoreManagement/PromotionManagement/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using FLexElectronicsShop.Data;
using FLexElectronicsShop.Model;

namespace FLexElectronicsShop.Pages.StoreManagement.PromotionManagement
{
    public class DeleteModel : PageModel
    {
        private readonly FLexElectronicsShop.Data.FEShopContext _context;

        public DeleteModel(FLexElectronicsShop.Data.FEShopContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Promotion Promotion { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var promotion = await _context.Promotions.FirstOrDefaultAsync(m => m.Id == id);

            if (promotion == null)
            {
                return NotFound();
            }
            else
            {
                Promotion = promotion;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var promotion = await _context.Promotions.FindAsync(id);
            if (promotion != null)
            {
                Promotion = promotion;
                _context.Promotions.Remove(Promotion);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

WebApplicationFLexElectronicsShop_ProjectRazorPages/Pages/DigitalProducts/Add.cshtml
@page
@model FLexElectronicsShop.Pages.DigitalProducts.AddModel
@{
    ViewData["Title"] = "Добавить продукт";
}

<form method="post">
    <div>
        <label>Название продукта</label>
        <input asp-for="product.Name" type="text" style="width: 400px" />
        <span asp-validation-for="product.Name" class="text-danger"></span>
    </div>
    <div>
        <label>Ссылка на фото</label>
        <input asp-for="product.URL" type="text" />
        <span asp-validation-for="product.URL" class="text-danger"></span>
    </div>
@*     <div>
        <label>Стоимость продукта</label>
        <input asp-for="product.Price" type="text" />
        <span asp-validation-for="product.Price" class="text-danger"></span>
    </div> *@
    <label>Описание продукта</label>
    <input asp-for="product.Description" type="text" style="width: 400px" />
    <span asp-validation-for="product.Description" class="text-danger"></span>
    <input type="submit" />
</form>

WebApplicationFLexElectronicsShop_ProjectRazorPages/Pages/DigitalProducts/Delete.cshtml
@page
@model FLexElectronicsShop.Pages.DigitalProducts.DeleteModel
@{
    ViewData["Title"] = "Удалить продукт";
}

<div class="container">
    <form method="post">
        <h1>Вы уверены, что хотите удалить продукт @Model.Product.Name</h1>
        @* <p>@Model.Product.Price</p> *@
        <button type="submit" asp-route-id="@Model.Product.Id" asp-page-handler="delete" class="btn btn-primary">Удалить</button>
    </form>
</div>

WebApplicationFLexElectronicsShop_ProjectRazorPages/Pages/DigitalProducts/Details.cshtml
@page
@model FLexElectronicsShop.Pages.DigitalProducts.DetailsModel
@{
    ViewData["Title"] = "Информация о товаре";
}

<div class="container my-5">
    <div class="row">
        <div class="col-md-5">
            <div class="main-img">
                <img class="img-fluid" src="@Model!.Product!.URL" alt="@Model.Product.Name" />
            </div>
        </div>
        <div class="col-md-7">
            <div class="main-description px-2">
                <div class="text-bold">
                    Название : @Model.Product.Name
                </div>
                <div> Описание : @Model.Product.Description</div>
                @* <span> Стоимость : @Model.Product.Price₽</span> *@
            </div>
        </div>
    </div>
</div>

WebApplicationFLexElectronicsShop_ProjectRazorPages/Pages/DigitalProducts/Edit.cshtml
@page
@model FLexElectronicsShop.Pages.DigitalProducts.EditModel
@{
    ViewData["Title"] = "Изменение продукта";
}
<form method="post">
    <div hidden="hidden">
        <input asp-for="Product.Id" type="number" />
    </div>
    <div>
        <label>Название продукта</label>
        <input asp-for="Product.Name" type="text" style="width: 400px" />
        <span asp-validation-for="Product.Name" class="text-danger"></span>
    </div>
    <div>
        <label>Ссылка на фото</label>
        <input asp-for="Product.URL" type="text" />
        <span asp-validation-for="Product.URL" class="text-danger"></span>
    </div>
    <div>
        <label>Описание продукта</label>
        <input asp-for="Product.Description" type="text" />
        <span asp-validation-for="Product.Description" class="text-danger"></span>
    </div>
        <div>
    <label>Стоимость продукта</label>
@*     <input asp-for="Product.Price" type="text" />
    <span asp-validation-for="Product.Price" class="text-danger"></span> *@
    </div>
    <button type="submit" asp-route-id="@Model.Product.Id" asp-page-handler="update" class="btn btn-primary">Обновить</button>
</form>

WebApplicationFLexElectronicsShop_ProjectRazorPages/Pages/DigitalProducts/Index.cshtml
@page
@model FLexElectronicsShop.Pages.DigitalProducts.IndexModel
@{
    ViewData["Title"] = "Каталог продуктов";
}

<div class="container-fluid" style="padding-top: 35px">
    <form method="get">
        <div class="form-group">
            <label for="categoryFilter">Категории товаров:</label>
            <select id="categoryFilter" asp-for="SelectedCategoryId" asp-items="Model.Categories" class="form-control" onchange="this.form.submit()">
                <option value="">Все категории</option>
            </select>
        </div>
    </form>
    <div class="row row-cols-4">
        @foreach (var product in Model.Products)
        {
            <div class="col mb-4">
                <div class="card h-100">
                    <img src="@product.URL" class="card-img-top" alt="@product.Name">
                    <div class="card-body d-flex flex-column">
                        <h5 class="card-title flex-grow-1">@product.Name</h5>
                        <div class="mt-auto">
                            <a asp-page="/DigitalProducts/Details" asp-route-id="@product.Id" class="btn btn-primary">Купить</a>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>